name: Paramita
title: Paramita Koley
url: https://paramita1024.github.io/
baseurl: ""
twitter_username:
github_username:  paramita1024
#linkedin_username: subhendu-khatuya-543140a8
description: Machine learning, Deep learning, NLP, Computer Vision and other areas of data science.
email: paramita2000@gmail.com
permalink: /blog/:year/:month/:day/:title
theme: minima

# Conversion
markdown: kramdown

plugins:
  - "disqus-for-jekyll"
  - jekyll-feed
  - jemoji

header_pages:
  - resume.md
  - publications.md
  - index.md
  #- projects.md
